Remove string-only docker-tag declaration as that's not supported
Config:
```
  post-processors {
    post-processor "docker-tag" {
      repository =  "debian"
      tags = "latest"
    }
  }
```

Output:
```
Error: Failed preparing post-processor-block "docker-tag" ""

  on ./config.pkr.hcl line 65:
  (source code not available)

./config.pkr.hcl:67,14-22: Incorrect attribute value type; Inappropriate value
for attribute "tags": list of string required.

==> Wait completed after 3 microseconds

==> Builds finished but no artifacts were created.
```