Fix wrong hcl docker-tag post-processor example (#69)
With the provided examples, packer threw the following error:
```
Error: Failed preparing post-processor-block "docker-import" ""

  on ./config.pkr.hcl line 64:
  (source code not available)

./config.pkr.hcl:66,13-23: Incorrect attribute value type; Inappropriate value
for attribute "tag": string required.



==> Wait completed after 2 microseconds

==> Builds finished but no artifacts were created.
```